version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: testdb
    ports:
      - "3000:3000"
    networks:
      - minha-rede

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - minha-rede

networks:
  minha-rede:

volumes:
  pgdata:
